services:
  db:
    image: postgres:16-alpine
    container_name: nexus_db
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: nexusstream
    ports:
      - "5432:5432"
