spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://localhost:5432/nexusstream
    username: dev_user
    password: dev_password
    driver-class-name:  org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
